/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TagLibrary */

#ifndef _Included_TagLibrary
#define _Included_TagLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TagLibrary
 * Method:    getTags
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_TagLibrary_getTags
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
